name: For Moreh users
description: Suggest an idea, change for this project, or report a bug
title: "[Request or Bug] ..."
labels: ["moreh"]
projects: ["dongjin-na/2"]
assignees: []  # Assignees should be an array or string, an empty array is acceptable

body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

  - type: textarea
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem is.

  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

  - type: textarea
    attributes:
      label: Desired Solution
      description: A clear and concise description of what you want to happen.

  - type: markdown
    attributes:
      value: |
        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context or screenshots about the feature request here.

  - type: textarea
    attributes:
      label: Additional Feature Context
      description: Add any other context or screenshots about the feature request here.

  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.

  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.

  - type: markdown
    attributes:
      value: |
        **Expected behavior**
        A clear and concise description of what you expected to happen.

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.

  - type: markdown
    attributes:
      value: |
        **Screenshots**
        If applicable, add screenshots to help explain your problem.

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: markdown
    attributes:
      value: |
        **Please complete the following environment information:**
        - OS: [e.g. Ubuntu 20.04]
        - Version of software (eg. commit)

  - type: input
    attributes:
      label: OS
      description: Operating system (e.g. Ubuntu 20.04)

  - type: input
    attributes:
      label: Software Version
      description: Version of software (eg. commit)

  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context about the problem here.

  - type: textarea
    attributes:
      label: Additional Bug Context
      description: Add any other context about the problem here.
