name: For Moreh users
description: Suggest an idea, change for this project, or report a bug
title: "[Request or Bug] ..."
labels: ["moreh"]
projects: ["dongjin-na/2"]
assignees: []  # Assignees should be an array or string, an empty array is acceptable
body: 
  - type: textarea
    attributes:
      label: Contents
      value: |
        **Problem Description:**

        **Desired Solution:**

        **Alternatives Considered:**

        **Feature Additional Context:**

        **Bug Description:**

        **Steps to Reproduce:**

        **Expected Behavior:**

        **Screenshots:**

        **Environment Information:**
        - OS: [e.g. Ubuntu 20.04]
        - Version of software (eg. commit)

        **Additional Bug Context:**


